version: '3.9'
services:
  db:
    image: postgres:14-alpine
    container_name: pg-heranca-db
    environment:
      - POSTGRES_DB=heranca-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    volumes:
      - .docker/heranca_data:/var/lib/postgresql
